services:
  running-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CRITERIA_VERSION: 1
    env_file:
      - .env

  todo_postgres:
    image: "postgres:17.5-alpine"
    container_name: todo_postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
