services:
  todo_app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: todo_app
    restart: no
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      todo_postgres:
        condition: service_healthy
    volumes:
      - ./backend/:/app #mount volume for Air

  todo_postgres:
    image: "postgres:17.5-alpine"
    container_name: todo_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/db-data/postgres/:/var/lib/postgresql/data/
