services:
  todo_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo_app
    restart: no
    ports:
      - "8080:8080"
    environment:
      CRITERIA_VERSION: 1
    env_file:
      - .env
    depends_on:
      - todo_postgres
    volumes:
      - ./:/app #mount volume for Air

  todo_postgres:
    image: "postgres:17.5-alpine"
    container_name: todo_postgres
    ports:
      - "5432:5432"
    restart: no
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
